### ISSUE TITLE
Can't download CSV schema

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Public-Enemy#84]
# How to reproduce

1. add a new questionnaire
2. in the parameter window, click on the link to the schema [0]
3. a new and blank window appears, no download starts (the URL is `https://api-personnalisation-conception-questionnaires-recette.dev.kube.insee.fr/api/questionnaires/ls3bwk2d/csv`)

[0]
![image](https://github.com/InseeFr/Public-Enemy/assets/1663283/c546c6a7-372b-493f-82e2-3278dd5650ef)

**Comment by laurentC35** [comment]
Authentification issue, we have 401 code result en new page
